name: OUCGO CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      JWC_LOGIN_URL: ${{ secrets.JWC_LOGIN_URL }}
      JWC_USERNAME: ${{ secrets.JWC_USERNAME }}
      JWC_PASSWORD: ${{ secrets.JWC_PASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.8'

      - name: Check Python version
        run: python --version

      - name: Install Backend dependencies
        run: pip install -r src/oucgo_service/requirements.txt

      - name: Django check
        run: python src/oucgo_service/manage.py check

      - name: Check pending migrations
        run: python src/oucgo_service/manage.py makemigrations --check --dry-run

      - name: Run Django tests
        run: python src/oucgo_service/manage.py test --verbosity 2